@urlBase = http://localhost:5000
GET {{urlBase}}/RegistroProductos/ HTTP/1.1
###
GET http://localhost:5000/RegistroProductos/000004d2e4e87dfcd0f5753d HTTP/1.1
###P
POST http://localhost:5000/RegistroProductos HTTP/1.1
content-type: application/json

{
    "idproducto":12345 , 
    "descripcion": "tarjero, agg node",
    "valorunitario": 3000 , 
    "estado": "disponible", 
   "fecharegistro": "12-12-2021" 
}


###
DELETE http://localhost:5000/RegistroProductos/617249c535c38b944e06c500 
###
PUT http://localhost:5000/registroproductos/616b5ce5e1c6cfe62809612c 
content-type: application/json

{
    "idproducto":12345 , 
    "descripcion": "tarjero, agg node",
    "valorunitario": 3000 , 
    "estado": "disponible", 
   "fecharegistro": "12-12-2021" 
}