

POST http://localhost:5000/RegistroUsuarios HTTP/1.1
content-type: application/json

{
            "cedula": 123456789, 
            "nombre": "carolain abanis perez",
            "correo": "carito@gmail.com", 
            "contraseña": "aaaaa"
}
